### ISSUE TITLE
No such directory

### ISSUE THREAD

**Issue by caseybecking** [lovette/mysql-to-mongo#1]
I get this error `: : No such directory` when I run this command `$ my2mo-fields schema.sql`

**Comment by lovette** [comment]
That message seems to indicate the output directory doesn't exist (the default is the current directory since you're not using the `-d` option). Can you run the script with `bash -x my2mo-fields.sh schema.sql` and see if anything looks out of order? (You can post the output here too if you want me to review.)

**Comment by Yoganandh** [comment]
I tried to execute this command $ my2mo-fields schema.sql  it displays 

Generating tables and fields from schema.sql...
awk: not an option: --re-interval

Fields directory is created but nothing inside it. "import.tables" will be created automatically OR i need to create it ??

**Comment by lovette** [comment]
The error message given seems to indicate that the version of `awk` that you have does not support the `--re-interval` command line option. Hence the my2mo-fields script is unable to complete. I've personally only tested this under CentOS 6. What operating system are you running and what version of `awk` does it have?

**Comment by Yoganandh** [comment]
@lovette
Thanks for your reply.
Am using Ubuntu 14.02 and awk version is 1.3.3
Can you help me out how to proceed on this further.

**Comment by Yoganandh** [comment]
@lovette What version of awk does you have?

**Comment by lovette** [comment]
Unfortunately, I'm bogged down on another project and can't investigate further. I've only ever run it on CentOS 6.1, so I have no firsthand knowledge that it ever worked on Ubuntu, or that it even runs on the latest CentOS. It's a straightforward shell script, so maybe you can poke around and see if a different `awk` command line option helps.

**Comment by sharrondenice** [comment]
I have this same issue as well.

**Comment by lovette** [comment]
I'm afraid you're on your own here. I have not used MongoDB or run these scripts since 2011. I hope you figure something out though, the scripts were very useful to me at the time!

**Comment by sharrondenice** [comment]
Hi Lovette, I found a solution it’s called Groovy! It’s great! Thanks
