### ISSUE TITLE
Allow for MYSQL connection to be remote

### ISSUE THREAD

**Issue by ashrocket** [lovette/mysql-to-mongo#2]
While the mysqldump command can easily be accomplished to a remote host, executing your generated sql script won't work on a remote host because OUTFILE is always local the MYSQL Server.  The following however does work.  Maybe you can add this as a mode.  You'd need to modify it to produce csv instead of sql export statements.

while read TBL; do echo "SELECT \* FROM $TBL" | mysql -uusername -ppassword -B -h hostname -P 3306 databasename |  gzip -9 -c > $TBL.tsv.gz ; done < tables.txt

**Comment by lovette** [comment]
Sorry for the 10 year delay in this response 😳 I haven't been in Mongo world in as many years. Good solution above but I'm going to archive this repo for now.
